### ISSUE TITLE
[P0] Docker Compose 3344 端口暴露可能导致数据库被黑

### ISSUE THREAD

**Issue by Innei** [mx-space/core#1109]
**紧急事项**：我们近期发现部分用户数据库遭到非法入侵。初步调查显示，此次安全事件可能与 Docker 容器中的 MongoDB 端口被公开暴露在互联网上有关。

**问题描述**：若您的 MongoDB 的端口在 Docker 容器中暴露在公网上，可能会增加被恶意攻击的风险。

**解决方案**：

1. 请立即检查您的 `docker-compose` 文件。如果您的配置与下面的类似：
```yaml
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '3344:27017'
    networks:
      - app-network
    restart: always
  redis:
    image: redis
    container_name: redis
```
那么您需要重点关注 `ports` 项。

2. 为了加强安全性，请将 `ports` 配置项中的 `'3344:27017'` 删除，从而防止外部访问。如果您仍然需要端口转发，请确保只在 `127.0.0.1` 上进行监听，这样可以确保只有本机可以访问，如：
```yaml
    ports:
      - '127.0.0.1:3344:27017'
```

3. 同样地，对于 Redis 服务，请也确保端口仅在 `127.0.0.1` 上监听。

**最后**，请定期检查并更新您的系统和服务，以确保其安全性。如果有任何疑问或需要进一步的帮助，请及时联系我们。
