### ISSUE TITLE
[Bug] 在同一机器上开启多mx-space docker服务似乎会有冲突

### ISSUE THREAD

**Issue by Miaoyww** [mx-space/core#1475]
### Describe the bug

我在一台机器上试图使用docker开启两个mx-space服务，它们两个总会有一个不工作。
主要问题出现在，无论在docker_compose.yml中设置什么名称的redis及mongo，mx-space容器内总是会尝试访问原来名称的redis和mongo服务，但名称以及端口我都已经修改过了。

如以下示例:

正常流程的yml，它是正常工作的: 

```
version: '3.8'

services:
  app:
    container_name: mx-server
    image: innei/mx-server:latest
    command: bash ./docker-run.sh
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - ALLOWED_ORIGINS
      - JWT_SECRET
      - ENCRYPT_KEY
      - ENCRYPT_ENABLE

    volumes:
      - ./data/mx-space:/root/.mx-space
    ports:
      - '127.0.0.1:2333:2333'
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:2333/api/v2/ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network
    restart: always
  redis:
    image: redis
    container_name: redis

    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

```

修改后的yml:
```
version: '3.8'

services:
  miao-app:
    container_name: miao-mx-server
    image: innei/mx-server:latest
    command: bash ./docker-run.sh
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - ALLOWED_ORIGINS
      - JWT_SECRET
      - ENCRYPT_KEY
      - ENCRYPT_ENABLE

    volumes:
      - ./data/mx-space:/root/.mx-space
    ports:
      - '127.0.0.1:3332:2333'
    depends_on:
      - miao-mongo
      - miao-redis
    links:
      - miao-mongo
      - miao-redis
    networks:
      - miao-app-network
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:2333/api/v2/ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  miao-mongo:
    container_name: miao-mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    networks:
      - miao-app-network
    restart: always
  miao-redis:
    image: redis
    container_name: miao-redis

    networks:
      - miao-app-network
    restart: always

networks:
  miao-app-network:
    driver: bridge
```
它会报错: 
```
[Nest] 1  - 02/18/2024, 12:02:25 PM     LOG 数据目录已经建好：/root/.mx-space
[Nest] 1  - 02/18/2024, 12:02:25 PM     LOG 临时目录已经建好：/tmp/mx-space
[Nest] 1  - 02/18/2024, 12:02:25 PM     LOG 日志目录已经建好：/root/.mx-space/log
[Nest] 1  - 02/18/2024, 12:02:25 PM     LOG 资源目录已经建好：/root/.mx-space/assets
[Nest] 1  - 02/18/2024, 12:02:25 PM     LOG 文件存放目录已经建好：/root/.mx-space/static
[Nest] 1  - 02/18/2024, 12:02:25 PM     LOG 文件回收站目录已经建好：/tmp/mx-space/trash
cwd:  /app

 ERROR  [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)


 ERROR  [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)


 ERROR  [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)


 ERROR  [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)


 ERROR  [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)


 ERROR  [ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

### Reproduction

above

### System Info

```Shell
Linux version 5.15.0-84-generic (buildd@lcy02-amd64-005) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023

Docker 
Client: Docker Engine - Community
 Version:           25.0.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghost** [comment]
Service name 不需要改 你只需要改 container name就可以了
```yml
version: '3.8'

services:
  app:
    container_name: miao-mx-server
    image: innei/mx-server:latest
    command: bash ./docker-run.sh
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - ALLOWED_ORIGINS
      - JWT_SECRET
      - ENCRYPT_KEY
      - ENCRYPT_ENABLE

    volumes:
      - ./data/mx-space:/root/.mx-space
    ports:
      - '127.0.0.1:3332:2333'
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    networks:
      - miao-app-network
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:2333/api/v2/ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  mongo:
    container_name: miao-mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    networks:
      - miao-app-network
    restart: always
  redis:
    image: redis
    container_name: miao-redis

    networks:
      - miao-app-network
    restart: always

networks:
  miao-app-network:
    driver: bridge
```
即可
